/**
 * CatMod AI Project Reviewer Logic
 * Extracts project.json and redirects to ChatGPT with a formatted prompt
 */

const fileInput = document.getElementById('fileInput');
const promptInput = document.getElementById('promptInput');
const sendBtn = document.getElementById('sendBtn');
const status = document.getElementById('status');

// Helper to set prompt from preset buttons
window.setPrompt = (text) => {
    promptInput.value = text;
    // Visually nudge the user to click send
    sendBtn.classList.add('ring-2', 'ring-blue-400');
    setTimeout(() => sendBtn.classList.remove('ring-2', 'ring-blue-400'), 500);
};

sendBtn.addEventListener('click', async () => {
    const file = fileInput.files[0];
    const userPrompt = promptInput.value.trim();

    if (!file) {
        status.innerText = "❌ Please upload a project file first.";
        return;
    }

    if (!userPrompt) {
        status.innerText = "❌ Please enter a prompt or choose a preset.";
        return;
    }

    status.innerText = "📂 Reading project data...";

    try {
        const zip = new JSZip();
        const loadedZip = await zip.loadAsync(file);
        
        // Scratch and PenguinMod projects store data in project.json
        const projectJsonFile = loadedZip.file("project.json");

        if (!projectJsonFile) {
            status.innerText = "❌ Error: Could not find project.json inside this file.";
            return;
        }

        const projectData = await projectJsonFile.async("string");
        
        status.innerText = "🚀 Preparing AI request...";

        // Build the system-style prompt as requested
        const finalPrompt = `This prompt is auto generated by 'https://mobilefriendlyallay.github.io/catmod-extra/ai.' A user wants to review a PenguinMod project with the prompt '${userPrompt}' If the user asks anything about costumes or sounds in it, tell them that you can't read the costumes or sounds unless they are uploaded. The JSON project is '${projectData}'`;

        // Encode for URL usage
        const encodedPrompt = encodeURIComponent(finalPrompt);
        
        // Redirect to ChatGPT
        window.location.href = `https://chatgpt.com/?q=${encodedPrompt}`;

    } catch (err) {
        console.error(err);
        status.innerText = "❌ Error reading file. Is it a valid .sb3 or .pmp project?";
    }
});
